#!python
# encoding: utf-8


SYMBOL_INFO_EN_2_CN = {
    'custom': '自定义',
    'chart_mode': '图表模式',
    'select': '选择',
    'visible': '可见',
    'session_deals': '会话交易',
    'session_buy_orders': '会话买入订单',
    'session_sell_orders': '会话卖出订单',
    'volume': '成交量',
    'volumehigh': '最高成交量',
    'volumelow': '最低成交量',
    'time': '时间',
    'digits': '小数位数',
    'spread': '点差',
    'spread_float': '浮动点差',
    'ticks_bookdepth': '报价簿深度',
    'trade_calc_mode': '交易计算模式',
    'trade_mode': '交易模式',
    'start_time': '开始时间',
    'expiration_time': '到期时间',
    'trade_stops_level': '交易止损级别',
    'trade_freeze_level': '交易冻结级别',
    'trade_exemode': '交易执行模式',
    'swap_mode': '掉期模式',
    'swap_rollover3days': '3日掉期滚动',
    'expiration_mode': '到期模式',
    'filling_mode': '填充模式',
    'order_mode': '订单模式',
    'order_gtc_mode': 'GTC订单模式',
    'option_mode': '期权模式',
    'option_right': '期权权利',
    'bid': '买入价',
    'bidhigh': '买入价上限',
    'bidlow': '买入价下限',
    'ask': '卖出价',
    'askhigh': '卖价上限',
    'asklow': '卖价下限',
    'last': '最新价',
    'lasthigh': '最新价上限',
    'lastlow': '最新价下限',
    'volume_real': '实际成交量',
    'volumehigh_real': '实际最高成交量',
    'volumelow_real': '实际最低成交量',
    'option_strike': '期权行权价',
    'point': '点值',
    'trade_tick_value': '交易跳动价值',
    'trade_tick_value_profit': '交易跳动盈利',
    'trade_tick_value_loss': '交易跳动亏损',
    'trade_tick_size': '交易跳动大小',
    'trade_contract_size': '交易合约大小',
    'trade_accrued_interest': '应计利息',
    'trade_face_value': '面值',
    'trade_liquidity_rate': '流动性比率',
    'margin_hedged': '对冲保证金',
    'price_change': '价格变化',
    'price_volatility': '价格波动率',
    'price_theoretical': '理论价格',
    'price_greeks_delta': '价格-德尔塔',
    'price_greeks_theta': '价格-西塔',
    'price_greeks_gamma': '价格-伽马',
    'price_greeks_vega': '价格-维加',
    'price_greeks_rho': '价格-罗',
    'price_greeks_omega': '价格-欧米茄',
    'price_sensitivity': '价格敏感性',
    'basis': '基差',
    'category': '类别',
    'currency_base': '基础货币',
    'currency_profit': '盈利货币',
    'currency_margin': '保证金货币',
    'bank': '银行',
    'description': '描述',
    'exchange': '交易所',
    'formula': '公式',
    'isin': 'ISIN代码',
    'name': '名称',
    'page': '页面',
    'path': '路径',
    'margin_hedged_use_leg': '对冲保证金使用腿',
    'volume_min': '最小成交量',
    'volume_max': '最大成交量',
    'volume_step': '成交量步长',
    'volume_limit': '成交量限制',
    'swap_long': '做多掉期',
    'swap_short': '做空掉期',
    'margin_initial': '初始保证金',
    'margin_maintenance': '维持保证金',
    'session_volume': '会话成交量',
    'session_turnover': '会话成交额',
    'session_interest': '会话利息',
    'session_buy_orders_volume': '会话买入订单成交量',
    'session_sell_orders_volume': '会话卖出订单成交量',
    'session_open': '会话开盘价',
    'session_close': '会话收盘价',
    'session_aw': '会话结算价',
    'session_price_settlement': '会话结算价格',
    'session_price_limit_min': '会话价格限制最小值',
    'session_price_limit_max': '会话价格限制最大值',
}

SYMBOL_INFO_CN_2_EN = { v: k for k, v in SYMBOL_INFO_EN_2_CN.items() }

# 减少重复创建 dict view，做适度预处理以提速并增强匹配鲁棒性
SYMBOL_INFO_cn2en_items = list(SYMBOL_INFO_CN_2_EN.items())
SYMBOL_INFO_en2cn_keys = list(SYMBOL_INFO_EN_2_CN.keys())
